spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    platform: oracle
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
      
  activemq:
    broker-url: tcp://127.0.0.1:61616?jms.useAsyncSend=true&wireFormat.tightEncodingEnabled=false
    user: admin
    password: admin
      
 