spring:
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: test
    password: 1234
    platform: oracle
    hikari:
      maximum-pool-size: 30
      minimum-idle: 30
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout: 10000
      validation-timeout: 10000
      
  activemq:
    broker-url: tcp://127.0.0.1:61616?jms.useAsyncSend=true&wireFormat.tightEncodingEnabled=false
    user: admin
    password: admin
    
  cache:
    jcache:
      config: classpath:ehcache.xml

  quartz:
        wait-for-jobs-to-complete-on-shutdown: true
        job-store-type: jdbc
        jdbc:
          initialize-schema: always
        properties:
          org:
            quartz:
              scheduler:
                instanceName: INTG-SMS
                instanceId: SMS
                skipUpdateCheck: true
              #          jobStore:
              #            class: org.quartz.simpl.RAMJobStore
              jobStore:
                class: org.quartz.impl.jdbcjobstore.JobStoreTX
                driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                useProperties: false
                tablePrefix: QRTZ_
                misfireThreshold: 60000
                clusterCheckinInterval: 1000
                isClustered: true
              plugin:
                shutdownhook:
                  class: org.quartz.plugins.management.ShutdownHookPlugin
                  cleanShutdown: true
              threadPool:
                class: org.quartz.simpl.SimpleThreadPool
                threadCount: 20
                threadPriority: 5
                threadsInheritContextClassLoaderOfInitializingThread: true
        overwrite-existing-jobs: true
        auto-startup: true
        startup-delay: 20000
      
 